use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Aktualizovat přes WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "Obnovit",
    update_frequency: "Interval aktualizace",
    one_minute: "1 minuta",
    five_minutes: "5 minut",
    fifteen_minutes: "15 minut",
    one_hour: "1 hodina",
    models: "Služby",
    claude_code_model: "Claude Code",
    codex_model: "ChatGPT",
    layout: "Rozložení",
    layout_side_by_side: "Vedle sebe",
    layout_stacked: "Pod sebou",
    settings: "Nastavení",
    start_with_windows: "Spouštět s Windows",
    reset_position: "Obnovit pozici",
    always_on_top: "Vždy navrchu",
    language: "Jazyk",
    system_default: "Podle systému",
    check_for_updates: "Zkontrolovat aktualizace",
    checking_for_updates: "Kontroluji aktualizace...",
    updates: "Aktualizace",
    update_in_progress: "Kontrola aktualizací už probíhá.",
    up_to_date: "Už máte nejnovější verzi.",
    up_to_date_short: "Aktuální",
    update_failed: "Automatická aktualizace se nezdařila",
    applying_update: "Instaluji aktualizaci...",
    update_to: "Aktualizovat na",
    update_available: "Je dostupná aktualizace",
    update_prompt_now: "Je dostupná verze {version}. Chcete aktualizovat teď?",
    exit: "Ukončit",
    show_widget: "Zobrazit okno",
    session_window: "5 h",
    weekly_window: "7 d",
    now: "teď",
    day_suffix: " d",
    hour_suffix: " h",
    minute_suffix: " m",
    second_suffix: " s",
    token_expired_title: "Chyba přihlášení Claude Code",
    token_expired_body: "Spusťte v terminálu 'claude', potom použijte '/login' a postupujte podle pokynů. Poté aplikaci obnovte nebo restartujte.",
    codex_token_expired_title: "Chyba přihlášení Codex",
    codex_token_expired_body: "Spusťte v terminálu 'codex' a postupujte podle pokynů k přihlášení. Poté aplikaci obnovte nebo restartujte.",
};
