use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "새로고침",
    update_frequency: "업데이트 주기",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    models: "모델",
    claude_code_model: "Claude Code",
    codex_model: "ChatGPT",
    layout: "Layout",
    layout_side_by_side: "Side by Side",
    layout_stacked: "Stacked",
    settings: "설정",
    start_with_windows: "Windows 시작 시 자동 실행",
    reset_position: "위치 초기화",
    always_on_top: "항상 위에 표시",
    language: "언어",
    system_default: "시스템 기본값",
    check_for_updates: "업데이트 확인",
    checking_for_updates: "업데이트 확인 중...",
    updates: "업데이트",
    update_in_progress: "이미 업데이트 확인이 진행 중입니다.",
    up_to_date: "이미 최신 버전입니다.",
    up_to_date_short: "최신",
    update_failed: "자동 업데이트를 완료할 수 없습니다",
    applying_update: "업데이트 적용 중...",
    update_to: "업데이트 대상",
    update_available: "업데이트 사용 가능",
    update_prompt_now: "버전 {version}을 사용할 수 있습니다. 지금 업데이트하시겠습니까?",
    exit: "종료",
    show_widget: "위젯 표시",
    session_window: "5시간",
    weekly_window: "7일",
    now: "지금",
    token_expired_title: "인증 오류",
    token_expired_body: "터미널에서 'claude'를 실행한 다음 '/login'을 사용하고 안내에 따라 진행하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "터미널에서 'codex'를 실행하고 로그인 안내를 따르세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
};
